begin;

-- Catálogo operacional de endpoints. Esta tabela contém apenas URLs públicas,
-- templates e nomes de variáveis; nunca armazene chaves, tokens ou DATABASE_URL.
create table if not exists public.api_endpoint_catalog (
  code text primary key,
  service text not null,
  config_location text not null default 'VERCEL_ENV'
    check (config_location in ('VERCEL_ENV', 'APPS_SCRIPT_PROPERTY', 'PUBLIC')),
  environment text not null default 'production',
  method text not null default 'GET',
  url_template text not null check (url_template ~ '^https://'),
  secret_env_var text,
  enabled boolean not null default true,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists api_endpoint_catalog_service_idx
  on public.api_endpoint_catalog (service, enabled);

create table if not exists public.vercel_env_catalog (
  name text primary key,
  value_kind text not null
    check (value_kind in ('secret', 'url', 'text', 'number', 'boolean')),
  required boolean not null default false,
  scopes text[] not null default array['production', 'preview']::text[],
  safe_value text,
  source_code text,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- URLs de produção e templates usados pelo backend. Chaves ficam somente em
-- Vercel Environment Variables ou nas Script Properties do Apps Script.
insert into public.api_endpoint_catalog
  (code, service, config_location, environment, method, url_template,
   secret_env_var, description)
values
  ('vercel.web', 'VERCEL', 'PUBLIC', 'production', 'GET',
   'https://autentikonuvem.vercel.app/', null,
   'Aplicação web AUTENTIKO OK NUVEM'),
  ('vercel.health', 'VERCEL', 'PUBLIC', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/health', null,
   'Healthcheck público'),
  ('vercel.health.deep', 'VERCEL', 'PUBLIC', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/health?deep=1', null,
   'Healthcheck com Neon, Supabase e provedores'),
  ('vercel.ai.analyze', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/ai/analyze', 'GEMINI_API_KEY / OPENROUTER_API_KEY',
   'Análise estruturada por IA'),
  ('vercel.audit.anchor', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/audit/anchor', 'AUT_DATA_API_KEY',
   'Âncora de auditoria'),
  ('vercel.contract.get', 'VERCEL', 'VERCEL_ENV', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/v1/contracts/{id}', 'AUT_DATA_API_KEY',
   'Consulta de contrato por UUID'),
  ('vercel.contract.issue', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/contracts/issue', 'AUT_DATA_API_KEY',
   'Emissão de contrato'),
  ('vercel.media.access_url', 'VERCEL', 'VERCEL_ENV', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/v1/media/access-url', 'AUT_MEDIA_SIGNING_SECRET',
   'URL assinada de mídia'),
  ('vercel.media.status', 'VERCEL', 'VERCEL_ENV', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/v1/media/status', 'AUT_MEDIA_SIGNING_SECRET',
   'Status de mídia'),
  ('vercel.media.uploads', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/media/uploads', 'SUPABASE_SERVICE_ROLE_KEY',
   'Início de upload'),
  ('vercel.media.uploads.complete', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/media/uploads/complete', 'SUPABASE_SERVICE_ROLE_KEY',
   'Conclusão de upload'),
  ('vercel.media.jobs.retry', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/media/jobs/retry', 'AUT_MEDIA_SIGNING_SECRET',
   'Reprocessamento de job'),
  ('vercel.providers.query', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/providers/query', 'TRANSPARENCIA_API_KEY / DATAJUD_API_KEY',
   'Consulta de provedores com cache'),
  ('vercel.search', 'VERCEL', 'VERCEL_ENV', 'production', 'GET',
   'https://autentikonuvem.vercel.app/api/v1/search', 'AUT_DATA_API_KEY',
   'Busca paginada por cursor'),
  ('vercel.sync.nuvem', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/sync/nuvem', 'AUT_DATA_SYNC_SECRET',
   'Sincronização Apps Script para Neon'),
  ('vercel.webhook.adobe', 'VERCEL', 'VERCEL_ENV', 'production', 'POST',
   'https://autentikonuvem.vercel.app/api/v1/webhooks/adobe', 'ADOBE_WEBHOOK_SECRET',
   'Webhook Adobe'),
  ('apps_script.ok_docs', 'GOOGLE_APPS_SCRIPT', 'APPS_SCRIPT_PROPERTY', 'production', 'GET',
   'https://script.google.com/macros/s/AKfycbxd7ArUlxizGscu3cjtzQjtkMU2JCA2NpVx_y5dhNz8_NXlBQwZnD3mKqR_GjOE2ZY8sQ/exec',
   null, 'Web app AUTENTIKO OK DOCS'),
  ('apps_script.nuvem.bridge', 'GOOGLE_APPS_SCRIPT', 'APPS_SCRIPT_PROPERTY', 'production', 'GET',
   'https://script.google.com/macros/s/AKfycbx-Wc74peh4DwB16yURN-pjsQxxKczVJYiRtD8qKE65Hw6MM23zHKXmvueyB9CBvZGz/exec',
   'AUTENTIKO_NUVEM_API_KEY', 'Ponte JSON AUTENTIKO OK NUVEM'),
  ('neon.rest', 'NEON', 'VERCEL_ENV', 'production', 'GET',
   'https://ep-rough-shape-axnxsml5.apirest.c-4.us-east-2.aws.neon.tech/neondb/rest/v1',
   'DATABASE_URL', 'Data API do Neon; o backend usa DATABASE_URL privado'),
  ('neon.auth', 'NEON', 'PUBLIC', 'production', 'POST',
   'https://ep-rough-shape-axnxsml5.neonauth.c-4.us-east-2.aws.neon.tech/neondb/auth',
   null, 'Endpoint de autenticação Neon'),
  ('neon.jwks', 'NEON', 'PUBLIC', 'production', 'GET',
   'https://ep-rough-shape-axnxsml5.neonauth.c-4.us-east-2.aws.neon.tech/neondb/auth/.well-known/jwks.json',
   null, 'Chaves públicas JWKS do Neon'),
  ('supabase.project', 'SUPABASE', 'VERCEL_ENV', 'production', 'GET',
   'https://kgcucxqtzqcsskhjfmzl.supabase.co', 'SUPABASE_SERVICE_ROLE_KEY',
   'Projeto Supabase'),
  ('supabase.rest', 'SUPABASE', 'VERCEL_ENV', 'production', 'GET',
   'https://kgcucxqtzqcsskhjfmzl.supabase.co/rest/v1', 'SUPABASE_SERVICE_ROLE_KEY',
   'REST interno do Supabase'),
  ('supabase.storage', 'SUPABASE', 'VERCEL_ENV', 'production', 'GET',
   'https://kgcucxqtzqcsskhjfmzl.storage.supabase.co', 'SUPABASE_SERVICE_ROLE_KEY',
   'Storage privado do Supabase'),
  ('brasilapi.cep', 'BRASIL_API', 'PUBLIC', 'production', 'GET',
   'https://brasilapi.com.br/api/cep/v2/{CEP}', null,
   'Consulta de CEP; não exige chave'),
  ('brasilapi.cnpj', 'BRASIL_API', 'PUBLIC', 'production', 'GET',
   'https://brasilapi.com.br/api/cnpj/v1/{CNPJ}', null,
   'Consulta de CNPJ; não exige chave'),
  ('cgu.transparencia', 'CGU', 'VERCEL_ENV', 'production', 'GET',
   'https://api.portaldatransparencia.gov.br/api-de-dados/', 'TRANSPARENCIA_API_KEY',
   'Portal da Transparência'),
  ('datajud.search', 'DATAJUD', 'VERCEL_ENV', 'production', 'POST',
   'https://api-publica.datajud.cnj.jus.br/api_publica_{TRIBUNAL}/_search', 'DATAJUD_API_KEY',
   'Consulta processual por tribunal'),
  ('gemini.generate', 'GEMINI', 'VERCEL_ENV', 'production', 'POST',
   'https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent', 'GEMINI_API_KEY',
   'Geração JSON pelo Gemini'),
  ('openrouter.chat', 'OPENROUTER', 'VERCEL_ENV', 'production', 'POST',
   'https://openrouter.ai/api/v1/chat/completions', 'OPENROUTER_API_KEY',
   'Fallback de IA compatível com chat completions')
on conflict (code) do update set
  service = excluded.service,
  config_location = excluded.config_location,
  environment = excluded.environment,
  method = excluded.method,
  url_template = excluded.url_template,
  secret_env_var = excluded.secret_env_var,
  description = excluded.description,
  updated_at = now();

-- Catálogo das variáveis esperadas pelo media-api. safe_value só é preenchido
-- quando não é segredo; o valor real deve ser cadastrado no Vercel.
insert into public.vercel_env_catalog
  (name, value_kind, required, scopes, safe_value, source_code, notes)
values
  ('SUPABASE_URL', 'url', true, array['production', 'preview'],
   'https://kgcucxqtzqcsskhjfmzl.supabase.co', 'media-api/src/lib/env.ts', 'URL pública do projeto'),
  ('SUPABASE_STORAGE_URL', 'url', false, array['production', 'preview'],
   'https://kgcucxqtzqcsskhjfmzl.storage.supabase.co', 'media-api/src/lib/storage.ts', 'Opcional; habilita storage explícito'),
  ('SUPABASE_SERVICE_ROLE_KEY', 'secret', true, array['production', 'preview'],
   null, 'media-api/src/lib/supabase.ts', 'Somente servidor; nunca publicar no browser'),
  ('AUT_MEDIA_SIGNING_SECRET', 'secret', true, array['production', 'preview'],
   null, 'media-api/src/lib/ticket.ts', 'Segredo HMAC com pelo menos 32 caracteres'),
  ('AUTENTIKO_ALLOWED_ORIGINS', 'text', true, array['production', 'preview'],
   'https://script.google.com', 'media-api/src/lib/env.ts', 'Origens separadas por vírgula'),
  ('AUT_DRIVE_SYNC_WORKER_ENABLED', 'boolean', false, array['production', 'preview'],
   'false', 'media-api/src/lib/env.ts', 'Ative somente após homologar o worker'),
  ('ADOBE_ENABLED', 'boolean', false, array['production', 'preview'],
   'false', 'media-api/src/lib/env.ts', 'Integração Adobe opcional'),
  ('ADOBE_CLIENT_ID', 'text', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Obrigatório apenas com Adobe habilitado'),
  ('ADOBE_CLIENT_SECRET', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Obrigatório apenas com Adobe habilitado'),
  ('ADOBE_WEBHOOK_SECRET', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Obrigatório apenas com Adobe habilitado'),
  ('ADOBE_MONTHLY_LIMIT', 'number', false, array['production', 'preview'], '500',
   'media-api/src/lib/env.ts', 'Limite mensal de operações Adobe'),
  ('DATABASE_URL', 'secret', true, array['production', 'preview'], null,
   'media-api/src/lib/data-env.ts', 'Connection string pooled do Neon; nunca colocar no frontend'),
  ('AUT_DATA_API_KEY', 'secret', true, array['production', 'preview'], null,
   'media-api/src/lib/data-auth.ts', 'Chave interna das rotas de dados'),
  ('AUT_DATA_SYNC_SECRET', 'secret', true, array['production', 'preview'], null,
   'media-api/src/lib/data-auth.ts', 'Segredo HMAC da sincronização'),
  ('AUT_DATA_ALLOWED_ORIGINS', 'text', true, array['production', 'preview'],
   'https://script.google.com,https://script.googleusercontent.com', 'media-api/src/lib/data-env.ts', 'Origens separadas por vírgula'),
  ('AUT_CONTRACT_FINAL_ENABLED', 'boolean', false, array['production', 'preview'], 'false',
   'media-api/src/lib/data-env.ts', 'Mantenha false até homologação jurídica'),
  ('TRANSPARENCIA_API_KEY', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Chave opcional do Portal da Transparência'),
  ('DATAJUD_API_KEY', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Chave opcional do DataJud'),
  ('GEMINI_API_KEY', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Chave opcional; use GEMINI_MODEL'),
  ('GEMINI_MODEL', 'text', false, array['production', 'preview'], 'gemini-flash-latest',
   'media-api/src/lib/ai-service.ts', 'Modelo Gemini'),
  ('OPENROUTER_API_KEY', 'secret', false, array['production', 'preview'], null,
   'media-api/src/lib/env.ts', 'Chave opcional de fallback'),
  ('OPENROUTER_MODEL', 'text', false, array['production', 'preview'], null,
   'media-api/src/lib/ai-service.ts', 'Modelo OpenRouter'),
  ('AUT_DATA_PUBLIC_URL', 'url', false, array['production', 'preview'],
   'https://autentikonuvem.vercel.app', 'media-api/src/lib/ai-service.ts', 'URL pública para identificação do cliente')
on conflict (name) do update set
  value_kind = excluded.value_kind,
  required = excluded.required,
  scopes = excluded.scopes,
  safe_value = excluded.safe_value,
  source_code = excluded.source_code,
  notes = excluded.notes,
  updated_at = now();

revoke all on table public.api_endpoint_catalog, public.vercel_env_catalog from public;

commit;
