var AUTENTIKO = Object.freeze({
  APP_NAME: 'AUTENTIKO OK NUVEM',
  APP_VERSION: '2.5.8',
  SPREADSHEET_ID: '1KxsKxHCRdznYQQjz1IGL04u3v_z1kHVDtx07uxT3fF8',
  TIMEZONE: 'America/Sao_Paulo',
  SESSION_HOURS: 12,
  EMAIL_TOKEN_MINUTES: 15,
  MAX_UPLOAD_MB: 6,
  CACHE_SECONDS: 60,
  ROLES: ['DESENVOLVEDOR', 'ADMINISTRADOR', 'GERENTE_GERAL', 'GERENTE_ADMINISTRATIVO', 'AUDITOR', 'ASSISTENTE_ADMINISTRATIVO', 'CORRETOR'],
  USER_STATUS: ['PENDENTE', 'ATIVO', 'BLOQUEADO', 'EXCLUIDO'],
  PROCESS_STATUS: [
    'RASCUNHO', 'PENDENTE', 'EM_ANALISE', 'PENDENTE_DOCUMENTO', 'PENDENTE_PROCESSO',
    'APROVADO_ADMINISTRATIVO', 'APROVADO_GERENCIAL', 'APROVADO_GERENTE_GERAL', 'FINALIZADO', 'EXCLUIDO'
  ],
  PROCESS_PHASES: ['CADASTRO', 'DOCUMENTACAO', 'ADMINISTRATIVO', 'GERENCIAL', 'GERENTE_GERAL', 'CONTRATO', 'AUDITORIA', 'FINALIZACAO'],
  WORKFLOW_STATES: Object.freeze([
    'COM_CORRETOR', 'AGUARDANDO_ADMINISTRATIVO', 'COM_ADMINISTRATIVO', 'DEVOLVIDO_CORRETOR',
    'AGUARDANDO_GERENTE', 'COM_GERENTE', 'CONTRATO_EM_PREPARACAO',
    'AGUARDANDO_GERENTE_GERAL', 'COM_GERENTE_GERAL',
    'AGUARDANDO_AUDITORIA', 'COM_AUDITOR', 'CONCLUIDO'
  ]),
  REVIEW_CATEGORIES: Object.freeze([
    'CONTRATOS', 'PAGAMENTOS', 'PROCURACOES', 'NEGOCIACOES',
    'LAUDO_VISTORIA', 'LAUDO_CAPTACAO', 'DOCUMENTOS_PESSOAIS'
  ]),
  PARTICIPANT_ROLES: Object.freeze([
    'LOCATARIO', 'SIGNATARIO', 'FIADOR', 'AVALISTA', 'PROPRIETARIO',
    'COMPRADOR', 'VENDEDOR', 'PROCURADOR', 'TESTEMUNHA'
  ]),
  PROPOSAL_TYPES: Object.freeze([
    'VENDA', 'COMPRA_IMOVEL', 'ALUGUEL_ANUAL', 'ALUGUEL_SEMESTRAL', 'ALUGUEL_TEMPORADA'
  ]),
  PROCESS_TYPES: [
    'CAPTACAO_HOMOLOGACAO_IMOVEL',
    'COMPRA_IMOVEL_FINANCIADO',
    'COMPRA_IMOVEL_AVISTA',
    'COMPRA_IMOVEL_PARCELADO',
    'ALUGUEL_TEMPORADA',
    'ALUGUEL_ANUAL',
    'ALUGUEL_SEMESTRAL',
    'ALUGUEL_TRIMESTRAL',
    'ALUGUEL_MENSAL',
    'LEGALIZACAO_IMOVEL',
    'LEGALIZACAO_TERRENO',
    'LEGALIZACAO_APARTAMENTO_CONDOMINIO',
    'IMOVEL_NA_PLANTA',
    'LEGALIZACAO_TERCEIROS'
  ],
  RENTAL_INCOME_TYPES: Object.freeze([
    'ALUGUEL_ANUAL',
    'ALUGUEL_SEMESTRAL',
    'ALUGUEL_TRIMESTRAL',
    'ALUGUEL_MENSAL'
  ]),
  INCOME_PROOF_DOCUMENT_IDS: Object.freeze([
    'DOC_EXTRATO_BANCARIO',
    'DOC_CONTRACHEQUE_OLERITE',
    'DOC_DECORE_ELETRONICO',
    'DOC_EXTRATO_INSS',
    'DOC_EXTRATO_FGTS',
    'DOC_DECLARACAO_IMPOSTO_RENDA',
    'DOC_DECLARACAO_RENDA_CONTADOR'
  ])
});

var AUTENTIKO_LABELS = Object.freeze({
  GERENTE_GERAL: 'Gerente geral',
  GERENTE_ADMINISTRATIVO: 'Gerente administrativo',
  ASSISTENTE_ADMINISTRATIVO: 'Administrativo',
  VENDA: 'Venda',
  COMPRA_IMOVEL: 'Compra de imóvel',
  LOCATARIO: 'Locatário',
  SIGNATARIO: 'Signatário',
  FIADOR: 'Fiador',
  AVALISTA: 'Avalista',
  PROPRIETARIO: 'Proprietário',
  COMPRADOR: 'Comprador',
  VENDEDOR: 'Vendedor',
  PROCURADOR: 'Procurador',
  TESTEMUNHA: 'Testemunha',
  CONTRATOS: 'Contratos',
  PAGAMENTOS: 'Pagamentos',
  PROCURACOES: 'Procurações',
  NEGOCIACOES: 'Negociações',
  LAUDO_VISTORIA: 'Laudo de vistoria',
  LAUDO_CAPTACAO: 'Laudo de captação',
  DOCUMENTOS_PESSOAIS: 'Documentos pessoais',
  CAPTACAO_HOMOLOGACAO_IMOVEL: 'Captação e homologação de imóvel',
  COMPRA_IMOVEL_FINANCIADO: 'Compra de imóvel financiado',
  COMPRA_IMOVEL_AVISTA: 'Compra de imóvel à vista',
  COMPRA_IMOVEL_PARCELADO: 'Compra de imóvel parcelado',
  ALUGUEL_TEMPORADA: 'Aluguel por temporada',
  ALUGUEL_ANUAL: 'Aluguel anual',
  ALUGUEL_SEMESTRAL: 'Aluguel semestral',
  ALUGUEL_TRIMESTRAL: 'Aluguel trimestral',
  ALUGUEL_MENSAL: 'Aluguel mensal',
  LEGALIZACAO_IMOVEL: 'Legalização de imóvel',
  LEGALIZACAO_TERRENO: 'Legalização de terreno',
  LEGALIZACAO_APARTAMENTO_CONDOMINIO: 'Legalização de apartamento em condomínio',
  IMOVEL_NA_PLANTA: 'Imóvel na planta',
  LEGALIZACAO_TERCEIROS: 'Legalização de terceiros'
});

var AUTENTIKO_PERMISSIONS = Object.freeze({
  PROCESSO_CRIAR: 'Criar processos',
  PROCESSO_VER_TODOS: 'Ver todos os processos',
  PROCESSO_EDITAR: 'Editar processos',
  PROCESSO_ANALISAR: 'Analisar e alterar status',
  PROCESSO_EXCLUIR: 'Excluir processos',
  PROCESSO_RESERVAR: 'Reservar processos',
  PROCESSO_ENCAMINHAR: 'Encaminhar processos',
  DOCUMENTO_CONFERIR: 'Conferir documentos',
  APROVACAO_ADMINISTRATIVA: 'Aprovar etapa administrativa',
  APROVACAO_GERENCIAL: 'Aprovar categorias gerenciais',
  APROVACAO_GERAL: 'Aprovar processo na Gerência Geral',
  PROPOSTA_GERIR: 'Criar e revisar propostas',
  PROPOSTA_ACEITAR: 'Aceitar propostas',
  CONTRATO_EMITIR: 'Emitir contratos',
  CONTRATO_MODELO_GERIR: 'Gerir modelos e cláusulas contratuais',
  AUDITORIA_FINALIZAR: 'Finalizar auditoria',
  ADITIVO_CRIAR: 'Criar aditivo de processo finalizado',
  DOCUMENTO_ENVIAR: 'Enviar documentos',
  DOCUMENTO_BAIXAR: 'Baixar documentos',
  DOCUMENTO_EXCLUIR: 'Excluir documentos',
  PENDENCIA_GERIR: 'Gerir pendências',
  ATUACAO_CRIAR: 'Registrar atuações',
  AUDITORIA_VER: 'Ver auditoria',
  USUARIO_GERIR: 'Gerir usuários',
  FORMULARIO_GERIR: 'Gerir formulários e documentos obrigatórios',
  CONFIGURACAO_GERIR: 'Gerir configurações',
  SISTEMA_MANUTENCAO: 'Ativar manutenção',
  BASE_CLIENTES_VER: 'Consultar a Carta de Clientes',
  BASE_CLIENTES_EDITAR: 'Editar cadastros mestres de clientes',
  BASE_IMOVEIS_VER: 'Consultar a base de imóveis',
  BASE_IMOVEIS_EDITAR: 'Editar cadastros mestres de imóveis',
  API_CHAVE_GERIR: 'Gerir chaves e integrações da API'
});

var AUTENTIKO_DEFAULT_PERMISSIONS = Object.freeze({
  DESENVOLVEDOR: ['*'],
  ADMINISTRADOR: [
    'PROCESSO_CRIAR', 'PROCESSO_VER_TODOS', 'PROCESSO_EDITAR', 'PROCESSO_ANALISAR', 'PROCESSO_ENCAMINHAR',
    'PROCESSO_RESERVAR', 'DOCUMENTO_ENVIAR', 'DOCUMENTO_BAIXAR', 'DOCUMENTO_EXCLUIR',
    'PENDENCIA_GERIR', 'ATUACAO_CRIAR', 'AUDITORIA_VER', 'USUARIO_GERIR',
    'FORMULARIO_GERIR', 'CONFIGURACAO_GERIR', 'CONTRATO_MODELO_GERIR',
    'PROPOSTA_GERIR', 'CONTRATO_EMITIR', 'ADITIVO_CRIAR',
    'BASE_CLIENTES_VER', 'BASE_IMOVEIS_VER', 'API_CHAVE_GERIR'
  ],
  GERENTE_ADMINISTRATIVO: [
    'PROCESSO_CRIAR', 'PROCESSO_VER_TODOS', 'PROCESSO_EDITAR', 'PROCESSO_ANALISAR', 'PROCESSO_ENCAMINHAR', 'PROCESSO_RESERVAR',
    'DOCUMENTO_ENVIAR', 'DOCUMENTO_BAIXAR', 'DOCUMENTO_EXCLUIR', 'DOCUMENTO_CONFERIR',
    'PENDENCIA_GERIR', 'ATUACAO_CRIAR', 'AUDITORIA_VER',
    'APROVACAO_ADMINISTRATIVA', 'APROVACAO_GERENCIAL', 'APROVACAO_GERAL', 'AUDITORIA_FINALIZAR',
    'PROPOSTA_GERIR', 'PROPOSTA_ACEITAR', 'CONTRATO_EMITIR', 'ADITIVO_CRIAR',
    'BASE_CLIENTES_VER', 'BASE_CLIENTES_EDITAR', 'BASE_IMOVEIS_VER', 'BASE_IMOVEIS_EDITAR'
  ],
  GERENTE_GERAL: [
    'PROCESSO_CRIAR', 'PROCESSO_VER_TODOS', 'PROCESSO_EDITAR', 'PROCESSO_ANALISAR', 'PROCESSO_ENCAMINHAR', 'PROCESSO_RESERVAR',
    'DOCUMENTO_ENVIAR', 'DOCUMENTO_BAIXAR', 'DOCUMENTO_EXCLUIR', 'DOCUMENTO_CONFERIR',
    'PENDENCIA_GERIR', 'ATUACAO_CRIAR', 'AUDITORIA_VER',
    'APROVACAO_ADMINISTRATIVA', 'APROVACAO_GERENCIAL', 'APROVACAO_GERAL', 'AUDITORIA_FINALIZAR',
    'PROPOSTA_GERIR', 'PROPOSTA_ACEITAR', 'CONTRATO_EMITIR', 'ADITIVO_CRIAR',
    'BASE_CLIENTES_VER', 'BASE_CLIENTES_EDITAR', 'BASE_IMOVEIS_VER', 'BASE_IMOVEIS_EDITAR'
  ],
  AUDITOR: [
    'PROCESSO_VER_TODOS', 'PROCESSO_ANALISAR', 'PROCESSO_ENCAMINHAR',
    'DOCUMENTO_BAIXAR', 'DOCUMENTO_CONFERIR', 'PENDENCIA_GERIR',
    'ATUACAO_CRIAR', 'AUDITORIA_VER', 'AUDITORIA_FINALIZAR'
  ],
  ASSISTENTE_ADMINISTRATIVO: [
    'PROCESSO_EDITAR', 'PROCESSO_ANALISAR', 'PROCESSO_ENCAMINHAR', 'PROCESSO_RESERVAR',
    'DOCUMENTO_ENVIAR', 'DOCUMENTO_BAIXAR', 'DOCUMENTO_CONFERIR',
    'PENDENCIA_GERIR', 'ATUACAO_CRIAR', 'APROVACAO_ADMINISTRATIVA'
  ],
  CORRETOR: [
    'PROCESSO_CRIAR', 'PROCESSO_ENCAMINHAR', 'DOCUMENTO_ENVIAR',
    'DOCUMENTO_BAIXAR', 'ATUACAO_CRIAR', 'PROPOSTA_GERIR'
  ]
});

var AUTENTIKO_SHEETS = Object.freeze({
  CONFIGURACOES: ['CHAVE', 'VALOR', 'GRUPO', 'TIPO', 'DESCRICAO', 'EDITAVEL', 'ATUALIZADO_EM', 'ATUALIZADO_POR'],
  USUARIOS: ['ID_USUARIO', 'NOME', 'EMAIL', 'USUARIO', 'SENHA_HASH', 'SALT', 'PERFIL', 'STATUS', 'PERMISSOES_JSON', 'EMAIL_VERIFICADO', 'CRIADO_EM', 'ATUALIZADO_EM', 'ULTIMO_ACESSO', 'TENTATIVAS_FALHAS', 'BLOQUEADO_ATE', 'DEVE_TROCAR_SENHA'],
  SESSOES: ['ID_SESSAO', 'ID_USUARIO', 'TOKEN_HASH', 'CRIADO_EM', 'EXPIRA_EM', 'REVOGADO_EM', 'DISPOSITIVO_JSON', 'LOCALIZACAO_JSON'],
  TOKENS_EMAIL: ['ID_TOKEN', 'ID_USUARIO', 'FINALIDADE', 'TOKEN_HASH', 'EXPIRA_EM', 'USADO_EM', 'CRIADO_EM'],
  API_CHAVES: ['ID_API', 'NOME', 'PREFIXO', 'CHAVE_HASH', 'ESCOPO_JSON', 'STATUS', 'CRIADO_EM', 'CRIADO_POR_ID', 'CRIADO_POR', 'ULTIMO_USO_EM', 'EXPIRA_EM', 'REVOGADO_EM', 'RATE_LIMIT_MIN', 'DESCRICAO'],
  PROCESSOS: [
    'ID_PROCESSO', 'PROTOCOLO', 'TIPO_PROCESSO', 'STATUS', 'FASE', 'ID_RESPONSAVEL', 'RESPONSAVEL',
    'ID_CRIADOR', 'CRIADOR', 'CLIENTE_NOME', 'CLIENTE_CPF', 'CLIENTE_RG', 'CLIENTE_EMAIL',
    'CLIENTE_CONTATO', 'CLIENTE_ENDERECO', 'TITULAR_NOME', 'IMOVEL_CODIGO', 'IMOVEL_ENDERECO',
    'DADOS_JSON', 'PENDENCIAS_QTD', 'RESERVADO_POR', 'RESERVADO_ATE', 'CRIADO_EM', 'ATUALIZADO_EM',
    'FINALIZADO_EM', 'EXCLUIDO_EM', 'SETOR_ATUAL', 'ENCAMINHADO_EM', 'ENCAMINHADO_POR',
    'STATUS_TRAMITACAO', 'ETAPA_ATUAL', 'VERSAO_REGISTRO', 'ID_ULTIMO_REMETENTE',
    'ULTIMO_REMETENTE', 'ID_ULTIMO_DESTINATARIO', 'ULTIMO_DESTINATARIO', 'AGUARDANDO_DESDE',
    'ANALISE_INICIADA_EM', 'BLOQUEADO_EM', 'BLOQUEADO_POR', 'HASH_MANIFESTO',
    'ID_PROCESSO_ORIGEM', 'TIPO_VINCULO', 'MIGRACAO_STATUS',
    'ID_CLIENTE_BASE', 'ID_TITULAR_BASE', 'ID_IMOVEL_BASE'
  ],
  PROCESSO_DADOS: [
    'ID_DADO', 'ID_PROCESSO', 'SECAO', 'CAMPO', 'ROTULO', 'VALOR', 'TIPO_DADO',
    'VERSAO_PROCESSO', 'ATIVO', 'LOTE_ATUALIZACAO', 'SUBSTITUIDO_EM', 'ATUALIZADO_EM'
  ],
  FORMULARIOS: ['ID_CAMPO', 'TIPO_PROCESSO', 'SECAO', 'CAMPO', 'ROTULO', 'TIPO_CAMPO', 'OPCOES_JSON', 'OBRIGATORIO', 'ORDEM', 'ATIVO', 'CONDICAO_JSON'],
  DOCUMENTOS_CATALOGO: ['ID_DOCUMENTO_TIPO', 'NOME_DOCUMENTO', 'TIPOS_PROCESSO_JSON', 'OBRIGATORIO', 'ATIVO', 'ORDEM', 'MIME_ACEITOS', 'TAMANHO_MAX_MB', 'CRIADO_EM', 'TIPOS_OBRIGATORIOS_JSON', 'CATEGORIAS_JSON'],
  PROCESSO_DOCUMENTOS: [
    'ID_DOCUMENTO', 'ID_PROCESSO', 'PROTOCOLO', 'ID_DOCUMENTO_TIPO', 'NOME_DOCUMENTO',
    'ARQUIVO_ID', 'ARQUIVO_NOME', 'MIME_TYPE', 'TAMANHO_BYTES', 'HASH_SHA256', 'VERSAO',
    'OBRIGATORIO', 'ENVIADO_POR', 'DISPOSITIVO_JSON', 'LOCALIZACAO_JSON', 'CRIADO_EM',
    'EXCLUIDO_EM', 'CATEGORIAS_JSON', 'STATUS_CONFERENCIA', 'CONFERIDO_EM', 'CONFERIDO_POR_ID',
    'CONFERIDO_POR', 'PENDENCIADO_EM', 'PENDENCIADO_POR', 'MOTIVO_PENDENCIA',
    'SUBSTITUIDO_POR', 'VERSAO_REGISTRO', 'BLOQUEADO_EM',
    'MEDIA_STATUS', 'MEDIA_VERSAO', 'THUMBNAIL_STATUS', 'PREVIEW_STATUS',
    'SYNC_DRIVE_SUPABASE', 'MEDIA_ATUALIZADO_EM', 'MEDIA_ERRO_CODIGO'
  ],
  PENDENCIAS: [
    'ID_PENDENCIA', 'ID_PROCESSO', 'TITULO', 'DESCRICAO', 'STATUS', 'RESPONSAVEL', 'PRAZO',
    'CRIADO_POR', 'CRIADO_EM', 'CONCLUIDO_EM', 'TIPO', 'TIPO_ALVO', 'ID_ALVO',
    'ID_USUARIO_RETORNO', 'USUARIO_RETORNO', 'CRIADO_POR_ID', 'CONCLUIDO_POR',
    'MOTIVO_CONCLUSAO', 'VERSAO_PROCESSO'
  ],
  ATUACOES: ['ID_ATUACAO', 'ID_PROCESSO', 'TIPO', 'DESCRICAO', 'STATUS_ANTERIOR', 'STATUS_NOVO', 'USUARIO', 'CRIADO_EM'],
  AUDITORIA: [
    'ID_AUDITORIA', 'SEQUENCIA', 'DATA_HORA', 'ID_USUARIO', 'USUARIO', 'ACAO', 'ENTIDADE',
    'ID_ENTIDADE', 'DETALHES_JSON', 'DISPOSITIVO_JSON', 'LOCALIZACAO_JSON', 'HASH_ANTERIOR',
    'HASH_ATUAL', 'ID_SESSAO', 'IP_PUBLICO', 'TIMEZONE', 'REQUEST_ID', 'PERFIL_USUARIO', 'VERSAO_HASH'
  ],
  LISTAS: ['TIPO', 'VALOR', 'ORDEM', 'ATIVO'],
  MOVIMENTACOES_PROCESSO: [
    'ID_MOVIMENTACAO', 'ID_PROCESSO', 'SEQUENCIA', 'ACAO', 'STATUS_ANTERIOR', 'STATUS_NOVO',
    'TRAMITACAO_ANTERIOR', 'TRAMITACAO_NOVA', 'ETAPA_ANTERIOR', 'ETAPA_NOVA',
    'ID_USUARIO_ORIGEM', 'USUARIO_ORIGEM', 'PERFIL_ORIGEM', 'ID_USUARIO_DESTINO',
    'USUARIO_DESTINO', 'PERFIL_DESTINO', 'OBSERVACAO', 'ID_MOVIMENTACAO_PAI',
    'ID_REQUISICAO', 'CRIADO_EM'
  ],
  PROCESSO_PARTICIPANTES: [
    'ID_PARTICIPANTE', 'ID_PROCESSO', 'TIPO_PESSOA', 'PAPEIS_JSON', 'NOME_RAZAO_SOCIAL',
    'NOME_FANTASIA', 'CPF_CNPJ', 'RG_IE', 'ORGAO_EXPEDIDOR', 'DATA_NASCIMENTO_ABERTURA',
    'NACIONALIDADE', 'ESTADO_CIVIL', 'REGIME_BENS', 'PROFISSAO', 'RENDA', 'EMPRESA_TRABALHO',
    'CARGO_FUNCAO', 'EMAIL', 'TELEFONE', 'ENDERECO_JSON', 'REPRESENTANTE_LEGAL',
    'DADOS_JSON', 'ID_CADASTRO_BASE', 'ORDEM', 'ATIVO', 'VERSAO_REGISTRO', 'CRIADO_EM', 'CRIADO_POR',
    'ATUALIZADO_EM', 'ATUALIZADO_POR'
  ],
  ACEITES_ELETRONICOS: [
    'ID_ACEITE', 'SEQUENCIA', 'ID_PROCESSO', 'TIPO_ESCOPO', 'ID_ESCOPO', 'VERSAO_ESCOPO',
    'HASH_CONTEUDO', 'CATEGORIA', 'DECISAO', 'TEXTO_ACEITE', 'ID_USUARIO', 'USUARIO',
    'PERFIL', 'ID_SESSAO', 'DATA_HORA', 'TIMEZONE', 'IP_PUBLICO', 'DISPOSITIVO_JSON',
    'LOCALIZACAO_JSON', 'ID_REQUISICAO', 'VERSAO_PROCESSO', 'HASH_ANTERIOR', 'HASH_ACEITE',
    'INVALIDADO_EM', 'MOTIVO_INVALIDACAO'
  ],
  PROCESSO_CHECKLIST: [
    'ID_CHECKLIST', 'ID_PROCESSO', 'CATEGORIA', 'STATUS', 'DECISAO', 'JUSTIFICATIVA',
    'HASH_CONJUNTO', 'VERSAO_PROCESSO', 'ID_ACEITE', 'DECIDIDO_EM', 'DECIDIDO_POR_ID',
    'DECIDIDO_POR', 'INVALIDADO_EM', 'MOTIVO_INVALIDACAO'
  ],
  PROPOSTAS: [
    'ID_PROPOSTA', 'ID_PROCESSO', 'NUMERO_PROPOSTA', 'TIPO_PROPOSTA', 'REVISAO', 'STATUS',
    'VALOR_INICIAL', 'VALOR_PROPOSTO', 'VALOR_NEGOCIADO', 'VALOR_ACEITO',
    'ID_PARTICIPANTE_OFERTANTE', 'ID_PARTICIPANTE_DESTINATARIO', 'ID_DOCUMENTO_EVIDENCIA',
    'OBSERVACOES', 'HASH_SNAPSHOT', 'VERSAO_PROCESSO', 'CRIADO_EM', 'CRIADO_POR_ID',
    'CRIADO_POR', 'ENVIADO_EM', 'ACEITO_EM', 'ACEITO_POR_ID', 'ACEITO_POR',
    'SUBSTITUIDO_EM', 'SUBSTITUIDO_POR_ID'
  ],
  PROPOSTA_CONDICOES: [
    'ID_CONDICAO', 'ID_PROPOSTA', 'ORDEM', 'TIPO_CONDICAO', 'DETALHES', 'CRIADO_EM'
  ],
  MODELOS_CONTRATO: [
    'ID_MODELO', 'TIPO_PROPOSTA', 'NOME_MODELO', 'TITULO_CONTRATO', 'VERSAO',
    'STATUS_JURIDICO', 'MARCA_DAGUA', 'ATIVO', 'CRIADO_EM', 'ATUALIZADO_EM', 'ATUALIZADO_POR'
  ],
  CLAUSULAS_CONTRATO: [
    'ID_CLAUSULA', 'ID_MODELO', 'ORDEM', 'TITULO', 'TEXTO', 'ATIVO', 'VERSAO',
    'STATUS_JURIDICO', 'CRIADO_EM', 'ATUALIZADO_EM', 'ATUALIZADO_POR'
  ],
  CONTRATOS: [
    'ID_CONTRATO', 'ID_PROCESSO', 'ID_PROPOSTA', 'ID_MODELO', 'NUMERO_CONTRATO',
    'REVISAO', 'TITULO', 'STATUS', 'ARQUIVO_HTML_ID', 'HASH_HTML', 'ARQUIVO_PDF_ID',
    'HASH_PDF', 'ARQUIVO_ASSINADO_ID', 'HASH_ASSINADO', 'VERSAO_PROCESSO',
    'MODELO_VERSAO', 'CRIADO_EM', 'CRIADO_POR_ID', 'CRIADO_POR', 'ASSINADO_EM',
    'CONFERIDO_EM', 'CONFERIDO_POR_ID', 'CONFERIDO_POR', 'SUBSTITUIDO_EM'
  ],
  CONTRATO_PARTES: [
    'ID_CONTRATO_PARTE', 'ID_CONTRATO', 'ID_PARTICIPANTE', 'PAPEIS_JSON',
    'NOME_RAZAO_SOCIAL', 'CPF_CNPJ', 'DADOS_JSON', 'ORDEM', 'HASH_PARTE'
  ],
  BASE_CLIENTES: [
    'ID_CADASTRO', 'TIPO_PESSOA', 'CPF_CNPJ', 'NOME_RAZAO_SOCIAL', 'NOME_FANTASIA',
    'RG_IE', 'ORGAO_EXPEDIDOR', 'DATA_NASCIMENTO_ABERTURA', 'NACIONALIDADE',
    'ESTADO_CIVIL', 'REGIME_BENS', 'PROFISSAO', 'RENDA', 'RENDA_ORIGEM',
    'EMPRESA_TRABALHO', 'CARGO_FUNCAO', 'EMAIL', 'TELEFONE', 'TELEFONE_RECADO',
    'CONTATO_RECADO_NOME', 'ENDERECO_JSON', 'REPRESENTANTE_LEGAL', 'DADOS_JSON',
    'PAPEIS_JSON', 'PROCESSOS_JSON', 'FONTES_JSON', 'CONFLITOS_ABERTOS', 'QUALIDADE',
    'STATUS', 'VERSAO_REGISTRO', 'CRIADO_EM', 'CRIADO_POR', 'ATUALIZADO_EM', 'ATUALIZADO_POR'
  ],
  BASE_CLIENTES_CONFLITOS: [
    'ID_CONFLITO', 'ID_CADASTRO', 'CPF_CNPJ_HASH', 'CAMPO', 'VALOR_ATUAL', 'VALOR_NOVO',
    'ID_PROCESSO_ORIGEM', 'FONTE', 'STATUS', 'CRIADO_EM', 'RESOLVIDO_EM', 'RESOLVIDO_POR'
  ],
  BASE_IMOVEIS: [
    'ID_IMOVEL', 'CHAVE_IMOVEL', 'CODIGO_INTERNO', 'MATRICULA', 'INSCRICAO_IPTU',
    'TIPO_IMOVEL', 'ENDERECO', 'ENDERECO_JSON', 'PROPRIETARIOS_JSON',
    'MODALIDADE_CAPTACAO', 'AUTORIZACAO_RYCKY_PALMER', 'STATUS_CAPTACAO',
    'DADOS_JSON', 'PROCESSOS_JSON', 'FONTES_JSON', 'STATUS', 'VERSAO_REGISTRO',
    'CRIADO_EM', 'CRIADO_POR', 'ATUALIZADO_EM', 'ATUALIZADO_POR'
  ]
});

var AUTENTIKO_PUBLIC_CONFIG_KEYS = Object.freeze([
  'NOME_SISTEMA', 'SUBTITULO', 'EMPRESA_NOME', 'EMPRESA_CNPJ', 'EMPRESA_ENDERECO',
  'EMPRESA_EMAIL', 'EMPRESA_EMAIL_COMERCIAL', 'EMPRESA_REPRESENTANTE', 'EMPRESA_CRECI',
  'LOGO_URL', 'COR_PRIMARIA', 'MODO_MANUTENCAO', 'MENSAGEM_MANUTENCAO', 'VERSAO_SISTEMA',
  'PDF_PREVIEW_ENABLED', 'MAX_PDF_SIZE_MB', 'MEDIA_CLOUD_ENABLED', 'MEDIA_API_BASE_URL',
  'MEDIA_MAX_UPLOAD_MB', 'MEDIA_MAX_PDF_SOURCE_MB', 'MEDIA_LARGE_UPLOAD_ENABLED',
  'MEDIA_DRIVE_SYNC_WORKER_READY', 'ADOBE_ENABLED'
]);
